AWSTemplateFormatVersion: '2010-09-09'
Description: 'API Template'
Resources:
  DemoVpcLink:
    Type: AWS::ApiGateway::VpcLink
    Properties:
      Name: 'Demo VPC Link'
      TargetArns:
        - !ImportValue DemoNlbArn

  DemoRestApi:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: 'Demo Rest Api'

  DemoProxyResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      ParentId: !GetAtt DemoRestApi.RootResourceId
      RestApiId: !Ref DemoRestApi
      PathPart: "{proxy+}"

  CognitoAuthorizer:
    Type: AWS::ApiGateway::Authorizer
    Properties:
      Name: 'cognito-authorizer'
      IdentitySource: 'method.request.header.Authorization'
      ProviderARNs:
        - 'arn:aws:cognito-idp:eu-west-3:360463448794:userpool/eu-west-3_lswiodBeZ'
      RestApiId: !Ref DemoRestApi
      Type: COGNITO_USER_POOLS

  ApiGatewayMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      AuthorizationType: COGNITO_USER_POOLS
      AuthorizerId: !Ref CognitoAuthorizer
      HttpMethod: ANY
      ResourceId: !Ref DemoProxyResource
      RestApiId: !Ref DemoRestApi
      RequestParameters:
        method.request.path.proxy: true
      Integration:
        IntegrationHttpMethod: ANY
        Type: HTTP_PROXY
        Uri: !Sub
          - 'http://${DemoNlbDns}/{proxy}'
          - DemoNlbDns: !ImportValue DemoNlbDns
        ConnectionType: VPC_LINK
        ConnectionId: !Ref DemoVpcLink
        RequestParameters:
          integration.request.path.proxy: 'method.request.path.proxy'
        PassthroughBehavior: WHEN_NO_TEMPLATES
        IntegrationResponses:
          - StatusCode: 200
