AWSTemplateFormatVersion: '2010-09-09'
Description: 'API Template'
Resources:
  DemoHttpApi:
    Type: AWS::ApiGatewayV2::Api
    Properties:
      Name: 'Demo Http Api'
      ProtocolType: HTTP

  DemoApiIntegration:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref DemoHttpApi
      IntegrationType: HTTP_PROXY
      IntegrationUri: !ImportValue DemoNLBListenerArn
      IntegrationMethod: ANY
      ConnectionType: VPC_LINK
      ConnectionId: !ImportValue DemoVpcLinkArn
      PayloadFormatVersion: 1.0
      RequestParameters:
        "overwrite:header.X-User-Roles": "$context.authorizer.claims.cognito_groups"
        "overwrite:path": "/$request.path.proxy"

  CognitoAuthorizer:
    Type: AWS::ApiGatewayV2::Authorizer
    Properties:
      Name: 'cognito-authorizer'
      ApiId: !Ref DemoHttpApi
      AuthorizerType: JWT
      IdentitySource:
        - "$request.header.Authorization"
      JwtConfiguration:
        Audience:
          - 3b913ptbln89jecm13l9hhk9pm
        Issuer: "https://cognito-idp.eu-west-3.amazonaws.com/eu-west-3_lswiodBeZ"

  DemoApiRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref DemoHttpApi
      RouteKey: ANY /demo-api/{proxy+}
      Target: !Sub "integrations/${DemoApiIntegration}"
      AuthorizationType: JWT
      AuthorizerId: !Ref CognitoAuthorizer

  DemoApiStage:
    Type: AWS::ApiGatewayV2::Stage
    Properties:
      ApiId: !Ref DemoHttpApi
      StageName: $default
      AutoDeploy: true
