AWSTemplateFormatVersion: '2010-09-09'
Description: 'Network Load Balancer Template'
Resources:
  DemoALBSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: 'NLB Security Group'
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: 0.0.0.0/0
      VpcId: !ImportValue DemoVpcId

  DemoApplicationLoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: 'demo-application-load-balancer'
      SecurityGroups:
        - !Ref DemoALBSecurityGroup
      Subnets:
        - !ImportValue DemoPublicSubnet1Id
        - !ImportValue DemoPublicSubnet2Id
      Scheme: internet-facing
      Type: application

  FargateTargetGroupDemo:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      HealthCheckPath: '/demo/health'
      Name: 'fargate-target-group'
      Protocol: HTTP
      Port: 5001
      VpcId: !ImportValue DemoVpcId
      TargetType: ip

  DemoALBListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      DefaultActions:
        - Type: authenticate-cognito
          Order: 1
          AuthenticateCognitoConfig:
            UserPoolArn: 'arn:aws:cognito-idp:eu-west-3:360463448794:userpool/eu-west-3_N9dmuTXSK'
            UserPoolClientId: 's7dtlu2ugb4qtk9q730a8lmc1'
            UserPoolDomain: 'eu-west-3n9dmutxsk.auth.eu-west-3.amazoncognito.com'
            OnUnauthenticatedRequest: 'deny'
        - TargetGroupArn: !Ref FargateTargetGroupDemo
          Order: 2
          Type: forward
      LoadBalancerArn: !Ref DemoApplicationLoadBalancer
      Port: 443
      Protocol: HTTPS
      Certificates:
        - CertificateArn: "arn:aws:acm:eu-west-3:360463448794:certificate/a5bccddd-6faf-45b1-a766-7bc252f729f8"

  ALBListenerRuleDemo:
    Type: AWS::ElasticLoadBalancingV2::ListenerRule
    Properties:
      Actions:
        - Type: forward
          TargetGroupArn: !Ref FargateTargetGroupDemo
      Conditions:
        - Field: path-pattern
          Values:
            - "/demo/*"
      ListenerArn: !Ref DemoALBListener
      Priority: 10

Outputs:
  FargateTargetGroupDemoArn:
    Value: !Ref FargateTargetGroupDemo
    Export:
      Name: FargateTargetGroupDemoArn
