AWSTemplateFormatVersion: '2010-09-09'
Description: 'Network Load Balancer Template'
Resources:
  DemoNLBSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: 'NLB Security Group'
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
      VpcId: !ImportValue DemoVpcId

  DemoNetworkLoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: 'demo-network-load-balancer'
      SecurityGroups:
        - !Ref DemoNLBSecurityGroup
      Subnets:
        - !ImportValue DemoPrivateSubnet1Id
        - !ImportValue DemoPrivateSubnet2Id
      Scheme: internal
      Type: network

  FargateTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: 'fargate-target-group'
      Protocol: TCP
      Port: 5001
      VpcId: !ImportValue DemoVpcId
      TargetType: ip

  DemoNLBListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      DefaultActions:
        - TargetGroupArn: !Ref FargateTargetGroup
          Type: forward
      LoadBalancerArn: !Ref DemoNetworkLoadBalancer
      Port: 80
      Protocol: TCP

Outputs:
  DemoNlbArn:
    Value: !Ref DemoNetworkLoadBalancer
    Export:
      Name: DemoNlbArn

  DemoNlbDns:
    Value: !GetAtt DemoNetworkLoadBalancer.DNSName
    Export:
      Name: DemoNlbDns

  FargateTargetGroupArn:
    Value: !Ref FargateTargetGroup
    Export:
      Name: FargateTargetGroupArn
