AWSTemplateFormatVersion: '2010-09-09'
Description: 'Network Load Balancer Template'
Resources:
  DemoALBSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: 'NLB Security Group'
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
      VpcId: !ImportValue DemoVpcId

  DemoApplicationLoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: 'demo-application-load-balancer'
      SecurityGroups:
        - !Ref DemoALBSecurityGroup
      Subnets:
        - !ImportValue DemoPublicSubnet1Id
        - !ImportValue DemoPublicSubnet2Id
      Scheme: internet-facing
      Type: application

  FargateTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: 'fargate-target-group'
      Protocol: HTTP
      Port: 5001
      VpcId: !ImportValue DemoVpcId
      TargetType: ip

  DemoNLBListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      DefaultActions:
        - TargetGroupArn: !Ref FargateTargetGroup
          Type: forward
      LoadBalancerArn: !Ref DemoApplicationLoadBalancer
      Port: 80
      Protocol: HTTP

Outputs:
  FargateTargetGroupArn:
    Value: !Ref FargateTargetGroup
    Export:
      Name: FargateTargetGroupArn
